# Versión de node
FROM node:18-alpine

WORKDIR /app

# Copia solo el package.json para aprovechar la caché de las capas de Docker
COPY package.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos
COPY . ./

# Construye la aplicación
RUN npm run build

# Expone el puerto 3000
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["npm", "start"]
